version: '3.8'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=bitnami
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@test.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 8888:80
volumes:
  postgresql_data:
    driver: local